# Generated by Django 4.2.11 on 2024-05-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, help_text='Just friendly image', null=True, upload_to='app/static/stock_images'),
        ),
    ]
