# Generated by Django 4.2.11 on 2024-05-12 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(help_text='Unique ID', primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date')),
                ('lastUpdate', models.DateTimeField(default=django.utils.timezone.now, help_text='Update date')),
                ('text', models.TextField(help_text='The rate itself')),
                ('author', models.ForeignKey(help_text='The customer who left the rate', on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='app.customer')),
            ],
            options={
                'db_table': 'rates',
                'ordering': ['id'],
            },
        ),
    ]
