# Generated by Django 4.2.11 on 2024-05-12 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.TextField(default=10, help_text='Rate from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
