# Generated by Django 4.2.11 on 2024-05-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='code',
            field=models.CharField(default='ZooZoo', help_text='The code itself', max_length=20),
        ),
        migrations.AddField(
            model_name='promo',
            name='discount',
            field=models.IntegerField(default=0, help_text='Discount of the promo'),
        ),
        migrations.AddField(
            model_name='sales',
            name='address',
            field=models.CharField(default='Minsk, Karbysheva 7', help_text='Address of the sale', max_length=150),
        ),
    ]
