# Generated by Django 4.2.11 on 2024-05-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_promo_code_promo_discount_sales_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='password',
            field=models.CharField(help_text='password', max_length=1500),
        ),
    ]
