from app.adminConfig.adminAbout import *
from app.adminConfig.adminCategory import *
from app.adminConfig.adminCustomer import *
from app.adminConfig.employeeAdmin import *
from app.adminConfig.faqAdmin import *
from app.adminConfig.newsAdmin import *
from app.adminConfig.orderAdmin import *
from app.adminConfig.productAdmin import *
from app.adminConfig.promoAdmin import *
from app.adminConfig.rateAdmin import *
from app.adminConfig.salesAdmin import *
from app.adminConfig.suppliersAdmin import *
from app.adminConfig.vacanciesAdmin import *
